#!/opt/local/bin/bash

set -exu -o pipefail

rm -rf _*

basedir="$(python -c "import os ; print(os.path.dirname(os.path.realpath(\"${BASH_SOURCE[0]}\")))")" # because 'readlink -e' does not exist on darwin

cd "${basedir}"

name="image2rect"

declare -A OS # requires bash4, on darwin use macports or homebrew
OS=( [linux]="${name}" [darwin]="${name}" [windows]="${name}.exe" )

for GOOS in "${!OS[@]}" ; do

    mkdir -p "_bin/${GOOS}"
    GOPATH="$(pwd)" GOOS="${GOOS}" GOARCH="amd64" go build "${name}.go"
    mv "${OS[${GOOS}]}" "_bin/${GOOS}"

done

os="$(uname | tr '[A-Z]' '[a-z]')"

exe="_bin/${os}/${OS[${GOOS}]}"

mkdir -p "_test/oshw"

echo "size seconds" > "_test/oshw/timing.data"

for size in 100 200 400 800 ; do

    out="_test/oshw/${size}"

	(time "${exe}" \
        -input "test/oshw/oshw-logo-${size}-px.png" \
        -threshold 63 -monochrome "${out}.png" \
        -animation-build "${out}.gif" \
        -svg "${out}.svg" \
        -report \
    ) 1> "${out}.rect" 2>  "${out}.log"

    sed -i '' -e '/^\s*$/d' "${out}.log"

    echo -ne "${size} " >> "_test/oshw/timing.data"
    perl -ne 'if (m/^real\s+([.0-9]+)m([.0-9]+)s/i) { print 60 * $1 + $2, "\n"; }' < "${out}.log" >> "_test/oshw/timing.data"

done

gnuplot << _EOD_
set term svg
set output '_test/oshw/timing.svg'
set key autotitle columnhead
set logscale y
set nokey
set xrange [10:1000]
set xlabel "image size / pixels"
set ylabel "run time / seconds"
plot '_test/oshw/timing.data' with points, '_test/oshw/timing.data' smooth cspline
_EOD_

for dir in misc color ; do
    mkdir -p "_test/${dir}"
    for file in "test/${dir}"/* ; do

        out="$(basename "${file}")"
        out="$(basename "${out}" .png)"
        out="$(basename "${out}" .jpg)"
        out="_test/${dir}/${out}"

        (time "${exe}" \
            -input "${file}" \
            -verify "${out}.png" \
            -invert -negative "${out}~neg.png" \
            -threshold 63 -monochrome "${out}~baw.png" \
            -animation-pixels "${out}~pix.gif" \
            -animation-build "${out}~bld.gif" \
            -svg "${out}.svg" \
            -report \
        ) 1> "${out}.rect" 2>  "${out}.log"

        sed -i '' -e '/^\s*$/d' "${out}.log"

    done
done
