#!/opt/local/bin/bash

set -exu -o pipefail

rm -rf _*

basedir="$(python -c "import os ; print(os.path.dirname(os.path.realpath(\"${BASH_SOURCE[0]}\")))")" # because 'readlink -e' does not exist on darwin

cd "${basedir}"

name="image2rect"

declare -A OS # requires bash4, on darwin use macports or homebrew
OS=( [linux]="${name}" [darwin]="${name}" [windows]="${name}.exe" )

for GOOS in "${!OS[@]}" ; do

    mkdir -p "_bin/${GOOS}"
    GOPATH="$(pwd)" GOOS="${GOOS}" GOARCH="amd64" go build "${name}.go"
    mv "${OS[${GOOS}]}" "_bin/${GOOS}"

done

os="$(uname | tr '[A-Z]' '[a-z]')"

exe="_bin/${os}/${OS[${GOOS}]}"

mkdir -p "_test"

echo "size seconds" > "_test/timing.data"

for size in 100 200 400 800 ; do

	(time "${exe}" \
        -input "oshw/oshw-logo-${size}-px.png" \
        -threshold 63 -monochrome "_test/${size}.png" \
        -animation-build "_test/${size}.gif" \
        -svg "_test/${size}.svg" \
        -report \
    ) 1> "_test/${size}.rect" 2>  "_test/${size}.log"

    sed -i '' -e '/^\s*$/d' "_test/${size}.log"

    echo -ne "${size} " >> "_test/timing.data"
    perl -ne 'if (m/^real\s+([.0-9]+)m([.0-9]+)s/i) { print 60 * $1 + $2, "\n"; }' < "_test/${size}.log" >> "_test/timing.data"

done

gnuplot << _EOD_
set term svg
set output '_test/timing.svg'
set key autotitle columnhead
set logscale y
set nokey
set xrange [10:1000]
set xlabel "image size / pixels"
set ylabel "run time / seconds"
plot '_test/timing.data' with points, '_test/timing.data' smooth cspline
_EOD_
